source 0, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
source 1, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
source 2, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
source 3, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
source 4, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
source 5, len=1
source=5	oldTarget=2	colNos[0]=0	meters[0]=[-7,0,2,7]
source 6, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
source 7, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
source 8, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
source 9, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
source 10, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
source 11, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
source 12, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
source 13, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
source 14, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
source 15, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
source 16, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
source 17, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
source 18, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
source 19, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
source 20, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
source 21, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
source 22, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
source 23, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
source 24, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
source 25, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
source 26, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
source 27, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
source 28, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
source 29, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
source 30, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
source 31, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
source 32, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
source 33, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
source 34, len=4
source=34	oldTarget=33	colNos[0]=0	meters[0]=[2,0,0,0]
source=34	oldTarget=33	colNos[1]=1	meters[1]=[0,2,0,0]
source=34	oldTarget=33	colNos[2]=2	meters[2]=[0,0,2,0]
source=34	oldTarget=33	colNos[3]=3	meters[3]=[0,0,0,2]
test 34 33	[585715960903147640,2556827383749699103,2024155336530384440,2778996090487120353]	[1171431921806295280,5113654767499398206,4048310673060768880,5557992180974240706]	idx=   0   1   2   3	amat=[[2,0,0,0],[0,2,0,0],[0,0,2,0],[0,0,0,2]], chain 8
source 35, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
source 36, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
source 37, len=0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.teherba.ramath.util.ModoMeter.setIndexRanges(ModoMeter.java:240)
	at org.teherba.ramath.eec.CandidateSelector.testMatrixChains(CandidateSelector.java:284)
	at org.teherba.ramath.eec.CandidateSelector.groupTargets(CandidateSelector.java:265)
	at org.teherba.ramath.eec.CandidateSelector.expand(CandidateSelector.java:214)
	at org.teherba.ramath.eec.CandidateSelector.main(CandidateSelector.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:630)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:733)
