java.io.FileNotFoundException: data/prewrob3.sub (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at org.teherba.ramath.util.Options.getVectors(Options.java:241)
	at org.teherba.ramath.util.Options.getVectors(Options.java:208)
	at org.teherba.ramath.linear.MatrixTester.main(MatrixTester.java:671)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:614)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:717)
0 of 0 failed,  NaN%
