IN_START,(, 	operStack=[y(], 	postfix=[]
IN_NUMBER,3, 	operStack=[y(], 	postfix=[]
IN_START,*, 	operStack=[y(], 	postfix=[3]
IN_OPERATOR,*, 	operStack=[y(], 	postfix=[3]
IN_START,a, 	operStack=[y(, p*], 	postfix=[3]
IN_NAME,a, 	operStack=[y(, p*], 	postfix=[3]
IN_START,², 	operStack=[y(, p*], 	postfix=[3, a]
IN_EXPONENT,², 	operStack=[y(, p*, q^], 	postfix=[3, a]
IN_START,+, 	operStack=[y(, p*, q^], 	postfix=[3, a, 2]
IN_START,+, 	operStack=[y(, m+], 	postfix=[3, a, 2, ^, *]
IN_NAME,b, 	operStack=[y(, m+], 	postfix=[3, a, 2, ^, *]
IN_START,^, 	operStack=[y(, m+], 	postfix=[3, a, 2, ^, *, b]
IN_START,^, 	operStack=[y(, m+, q^], 	postfix=[3, a, 2, ^, *, b]
IN_NUMBER,2, 	operStack=[y(, m+, q^], 	postfix=[3, a, 2, ^, *, b]
IN_START,), 	operStack=[y(, m+, q^], 	postfix=[3, a, 2, ^, *, b, 2]
IN_CLOSE,), 	operStack=[], 	postfix=[3, a, 2, ^, *, b, 2, ^, +]
IN_START,-, 	operStack=[], 	postfix=[3, a, 2, ^, *, b, 2, ^, +]
IN_START,-, 	operStack=[m-], 	postfix=[3, a, 2, ^, *, b, 2, ^, +]
IN_NUMBER,3, 	operStack=[m-], 	postfix=[3, a, 2, ^, *, b, 2, ^, +]
IN_START,*, 	operStack=[m-], 	postfix=[3, a, 2, ^, *, b, 2, ^, +, 3]
IN_OPERATOR,*, 	operStack=[m-], 	postfix=[3, a, 2, ^, *, b, 2, ^, +, 3]
IN_START,(, 	operStack=[m-, p*], 	postfix=[3, a, 2, ^, *, b, 2, ^, +, 3]
IN_START,(, 	operStack=[m-, p*, y(], 	postfix=[3, a, 2, ^, *, b, 2, ^, +, 3]
IN_NAME,c, 	operStack=[m-, p*, y(], 	postfix=[3, a, 2, ^, *, b, 2, ^, +, 3]
IN_START,², 	operStack=[m-, p*, y(], 	postfix=[3, a, 2, ^, *, b, 2, ^, +, 3, c]
IN_EXPONENT,², 	operStack=[m-, p*, y(, q^], 	postfix=[3, a, 2, ^, *, b, 2, ^, +, 3, c]
IN_START,+, 	operStack=[m-, p*, y(, q^], 	postfix=[3, a, 2, ^, *, b, 2, ^, +, 3, c, 2]
IN_START,+, 	operStack=[m-, p*, y(, m+], 	postfix=[3, a, 2, ^, *, b, 2, ^, +, 3, c, 2, ^]
IN_NAME,d, 	operStack=[m-, p*, y(, m+], 	postfix=[3, a, 2, ^, *, b, 2, ^, +, 3, c, 2, ^]
IN_START,^, 	operStack=[m-, p*, y(, m+], 	postfix=[3, a, 2, ^, *, b, 2, ^, +, 3, c, 2, ^, d]
IN_START,^, 	operStack=[m-, p*, y(, m+, q^], 	postfix=[3, a, 2, ^, *, b, 2, ^, +, 3, c, 2, ^, d]
IN_NUMBER,2, 	operStack=[m-, p*, y(, m+, q^], 	postfix=[3, a, 2, ^, *, b, 2, ^, +, 3, c, 2, ^, d]
IN_START,), 	operStack=[m-, p*, y(, m+, q^], 	postfix=[3, a, 2, ^, *, b, 2, ^, +, 3, c, 2, ^, d, 2]
IN_CLOSE,), 	operStack=[m-, p*], 	postfix=[3, a, 2, ^, *, b, 2, ^, +, 3, c, 2, ^, d, 2, ^, +]
IN_START,+, 	operStack=[m-, p*], 	postfix=[3, a, 2, ^, *, b, 2, ^, +, 3, c, 2, ^, d, 2, ^, +]
IN_START,+, 	operStack=[m+], 	postfix=[3, a, 2, ^, *, b, 2, ^, +, 3, c, 2, ^, d, 2, ^, +, *, -]
IN_NUMBER,0, 	operStack=[m+], 	postfix=[3, a, 2, ^, *, b, 2, ^, +, 3, c, 2, ^, d, 2, ^, +, *, -]
IN_START,*, 	operStack=[m+], 	postfix=[3, a, 2, ^, *, b, 2, ^, +, 3, c, 2, ^, d, 2, ^, +, *, -, 0]
IN_OPERATOR,*, 	operStack=[m+], 	postfix=[3, a, 2, ^, *, b, 2, ^, +, 3, c, 2, ^, d, 2, ^, +, *, -, 0]
IN_START,e, 	operStack=[m+, p*], 	postfix=[3, a, 2, ^, *, b, 2, ^, +, 3, c, 2, ^, d, 2, ^, +, *, -, 0]
IN_NAME,e, 	operStack=[m+, p*], 	postfix=[3, a, 2, ^, *, b, 2, ^, +, 3, c, 2, ^, d, 2, ^, +, *, -, 0]
[3, a, 2, ^, *, b, 2, ^, +, 3, c, 2, ^, d, 2, ^, +, *, -, 0, *, +]
