old IN_START'(' 	OS=[]	PF=[]
old IN_START'(' 	OS=[y(]	PF=[]
old IN_START'3' 	OS=[y(, y(]	PF=[]
old IN_NUMBER'*' 	OS=[y(, y(]	PF=[]
old IN_START'*' 	OS=[y(, y(]	PF=[3]
old IN_RELOP'a' 	OS=[y(, y(]	PF=[3]
old IN_START'a' 	OS=[y(, y(, p*]	PF=[3]
old IN_VNAME'²' 	OS=[y(, y(, p*]	PF=[3]
old IN_START'²' 	OS=[y(, y(, p*]	PF=[3, a]
old IN_EXPONENT'+' 	OS=[y(, y(, p*, q^]	PF=[3, a]
old IN_START'+' 	OS=[y(, y(, p*, q^]	PF=[3, a, 2]
old IN_START'b' 	OS=[y(, y(, m+]	PF=[3, a, 2, ^, *]
old IN_VNAME'^' 	OS=[y(, y(, m+]	PF=[3, a, 2, ^, *]
old IN_START'^' 	OS=[y(, y(, m+]	PF=[3, a, 2, ^, *, b]
old IN_START'2' 	OS=[y(, y(, m+, q^]	PF=[3, a, 2, ^, *, b]
old IN_NUMBER')' 	OS=[y(, y(, m+, q^]	PF=[3, a, 2, ^, *, b]
old IN_START')' 	OS=[y(, y(, m+, q^]	PF=[3, a, 2, ^, *, b, 2]
old IN_CLOSE'-' 	OS=[y(]	PF=[3, a, 2, ^, *, b, 2, ^, +]
old IN_START'-' 	OS=[y(]	PF=[3, a, 2, ^, *, b, 2, ^, +]
old IN_START'3' 	OS=[y(, m-]	PF=[3, a, 2, ^, *, b, 2, ^, +]
old IN_NUMBER'*' 	OS=[y(, m-]	PF=[3, a, 2, ^, *, b, 2, ^, +]
old IN_START'*' 	OS=[y(, m-]	PF=[3, a, 2, ^, *, b, 2, ^, +, 3]
old IN_RELOP'(' 	OS=[y(, m-]	PF=[3, a, 2, ^, *, b, 2, ^, +, 3]
old IN_START'(' 	OS=[y(, m-, p*]	PF=[3, a, 2, ^, *, b, 2, ^, +, 3]
old IN_START'c' 	OS=[y(, m-, p*, y(]	PF=[3, a, 2, ^, *, b, 2, ^, +, 3]
old IN_VNAME'²' 	OS=[y(, m-, p*, y(]	PF=[3, a, 2, ^, *, b, 2, ^, +, 3]
old IN_START'²' 	OS=[y(, m-, p*, y(]	PF=[3, a, 2, ^, *, b, 2, ^, +, 3, c]
old IN_EXPONENT'+' 	OS=[y(, m-, p*, y(, q^]	PF=[3, a, 2, ^, *, b, 2, ^, +, 3, c]
old IN_START'+' 	OS=[y(, m-, p*, y(, q^]	PF=[3, a, 2, ^, *, b, 2, ^, +, 3, c, 2]
old IN_START'd' 	OS=[y(, m-, p*, y(, m+]	PF=[3, a, 2, ^, *, b, 2, ^, +, 3, c, 2, ^]
old IN_VNAME'^' 	OS=[y(, m-, p*, y(, m+]	PF=[3, a, 2, ^, *, b, 2, ^, +, 3, c, 2, ^]
old IN_START'^' 	OS=[y(, m-, p*, y(, m+]	PF=[3, a, 2, ^, *, b, 2, ^, +, 3, c, 2, ^, d]
old IN_START'2' 	OS=[y(, m-, p*, y(, m+, q^]	PF=[3, a, 2, ^, *, b, 2, ^, +, 3, c, 2, ^, d]
old IN_NUMBER')' 	OS=[y(, m-, p*, y(, m+, q^]	PF=[3, a, 2, ^, *, b, 2, ^, +, 3, c, 2, ^, d]
old IN_START')' 	OS=[y(, m-, p*, y(, m+, q^]	PF=[3, a, 2, ^, *, b, 2, ^, +, 3, c, 2, ^, d, 2]
old IN_CLOSE'+' 	OS=[y(, m-, p*]	PF=[3, a, 2, ^, *, b, 2, ^, +, 3, c, 2, ^, d, 2, ^, +]
old IN_START'+' 	OS=[y(, m-, p*]	PF=[3, a, 2, ^, *, b, 2, ^, +, 3, c, 2, ^, d, 2, ^, +]
old IN_START'0' 	OS=[y(, m+]	PF=[3, a, 2, ^, *, b, 2, ^, +, 3, c, 2, ^, d, 2, ^, +, *, -]
old IN_NUMBER'*' 	OS=[y(, m+]	PF=[3, a, 2, ^, *, b, 2, ^, +, 3, c, 2, ^, d, 2, ^, +, *, -]
old IN_START'*' 	OS=[y(, m+]	PF=[3, a, 2, ^, *, b, 2, ^, +, 3, c, 2, ^, d, 2, ^, +, *, -, 0]
old IN_RELOP'e' 	OS=[y(, m+]	PF=[3, a, 2, ^, *, b, 2, ^, +, 3, c, 2, ^, d, 2, ^, +, *, -, 0]
old IN_START'e' 	OS=[y(, m+, p*]	PF=[3, a, 2, ^, *, b, 2, ^, +, 3, c, 2, ^, d, 2, ^, +, *, -, 0]
old IN_VNAME')' 	OS=[y(, m+, p*]	PF=[3, a, 2, ^, *, b, 2, ^, +, 3, c, 2, ^, d, 2, ^, +, *, -, 0]
old IN_START')' 	OS=[y(, m+, p*]	PF=[3, a, 2, ^, *, b, 2, ^, +, 3, c, 2, ^, d, 2, ^, +, *, -, 0, e]
result postfix=[3, a, 2, ^, *, b, 2, ^, +, 3, c, 2, ^, d, 2, ^, +, *, -, 0, e, *, +]
[3, a, 2, ^, *, b, 2, ^, +, 3, c, 2, ^, d, 2, ^, +, *, -, 0, e, *, +]
