IN_START,(, 	operStack=[y(], 	postfix=[]
IN_NUMBER,1, 	operStack=[y(], 	postfix=[]
IN_START,/, 	operStack=[y(], 	postfix=[1]
IN_START,/, 	operStack=[y(, p/], 	postfix=[1]
IN_START,(, 	operStack=[y(, p/, y(], 	postfix=[1]
IN_NUMBER,1, 	operStack=[y(, p/, y(], 	postfix=[1]
IN_START,-, 	operStack=[y(, p/, y(], 	postfix=[1, 1]
IN_START,-, 	operStack=[y(, p/, y(, m-], 	postfix=[1, 1]
IN_NAME,x, 	operStack=[y(, p/, y(, m-], 	postfix=[1, 1]
IN_START,-, 	operStack=[y(, p/, y(, m-], 	postfix=[1, 1, x]
IN_START,-, 	operStack=[y(, p/, y(, m-], 	postfix=[1, 1, x, -]
IN_NAME,x, 	operStack=[y(, p/, y(, m-], 	postfix=[1, 1, x, -]
IN_START,*, 	operStack=[y(, p/, y(, m-], 	postfix=[1, 1, x, -, x]
IN_OPERATOR,*, 	operStack=[y(, p/, y(, m-], 	postfix=[1, 1, x, -, x]
IN_START,*, 	operStack=[y(, p/, y(, m-, q^], 	postfix=[1, 1, x, -, x]
IN_NUMBER,2, 	operStack=[y(, p/, y(, m-, q^], 	postfix=[1, 1, x, -, x]
IN_START,), 	operStack=[y(, p/, y(, m-, q^], 	postfix=[1, 1, x, -, x, 2]
IN_CLOSE,), 	operStack=[y(, p/], 	postfix=[1, 1, x, -, x, 2, ^, -]
IN_START,), 	operStack=[y(, p/], 	postfix=[1, 1, x, -, x, 2, ^, -]
IN_CLOSE,), 	operStack=[], 	postfix=[1, 1, x, -, x, 2, ^, -, /]
result postfix=[1, 1, x, -, x, 2, ^, -, /]
[1, 1, x, -, x, 2, ^, -, /]
