old IN_START'(' 	OS=[]	PF=[]
old IN_START'1' 	OS=[y(]	PF=[]
old IN_NUMBR'/' 	OS=[y(]	PF=[]
old IN_START'/' 	OS=[y(]	PF=[1]
old IN_START'(' 	OS=[y(, p/]	PF=[1]
old IN_START'1' 	OS=[y(, p/, y(]	PF=[1]
old IN_NUMBR'-' 	OS=[y(, p/, y(]	PF=[1]
old IN_START'-' 	OS=[y(, p/, y(]	PF=[1, 1]
old IN_START'x' 	OS=[y(, p/, y(, m-]	PF=[1, 1]
old IN_VNAME'-' 	OS=[y(, p/, y(, m-]	PF=[1, 1]
old IN_START'-' 	OS=[y(, p/, y(, m-]	PF=[1, 1, x]
old IN_START'x' 	OS=[y(, p/, y(, m-]	PF=[1, 1, x, -]
old IN_VNAME'*' 	OS=[y(, p/, y(, m-]	PF=[1, 1, x, -]
old IN_START'*' 	OS=[y(, p/, y(, m-]	PF=[1, 1, x, -, x]
old IN_OPTOR'*' 	OS=[y(, p/, y(, m-]	PF=[1, 1, x, -, x]
old IN_START'2' 	OS=[y(, p/, y(, m-, q^]	PF=[1, 1, x, -, x]
old IN_NUMBR')' 	OS=[y(, p/, y(, m-, q^]	PF=[1, 1, x, -, x]
old IN_START')' 	OS=[y(, p/, y(, m-, q^]	PF=[1, 1, x, -, x, 2]
old IN_CLOSE')' 	OS=[y(, p/]	PF=[1, 1, x, -, x, 2, ^, -]
old IN_START')' 	OS=[y(, p/]	PF=[1, 1, x, -, x, 2, ^, -]
result postfix=[1, 1, x, -, x, 2, ^, -, /]
[1, 1, x, -, x, 2, ^, -, /]
