old IN_START'(' 	OS=[]	PF=[]
old IN_START'a' 	OS=[y(]	PF=[]
old IN_VNAME'(' 	OS=[y(]	PF=[]
old IN_START'n' 	OS=[y(, z(]	PF=[a(]
old IN_VNAME')' 	OS=[y(, z(]	PF=[a(]
old IN_START')' 	OS=[y(, z(]	PF=[a(, n]
old IN_CLOSE'=' 	OS=[y(]	PF=[a(, n, a)]
old IN_START'=' 	OS=[y(]	PF=[a(, n, a)]
old IN_OPTOR's' 	OS=[y(]	PF=[a(, n, a)]
old IN_START's' 	OS=[y(, l=]	PF=[a(, n, a)]
old IN_VNAME'q' 	OS=[y(, l=]	PF=[a(, n, a)]
old IN_VNAME'r' 	OS=[y(, l=]	PF=[a(, n, a)]
old IN_VNAME't' 	OS=[y(, l=]	PF=[a(, n, a)]
old IN_VNAME'(' 	OS=[y(, l=]	PF=[a(, n, a)]
old IN_START'2' 	OS=[y(, l=, z(]	PF=[a(, n, a), sqrt(]
old IN_NUMBR'*' 	OS=[y(, l=, z(]	PF=[a(, n, a), sqrt(]
old IN_START'*' 	OS=[y(, l=, z(]	PF=[a(, n, a), sqrt(, 2]
old IN_OPTOR'a' 	OS=[y(, l=, z(]	PF=[a(, n, a), sqrt(, 2]
old IN_START'a' 	OS=[y(, l=, z(, p*]	PF=[a(, n, a), sqrt(, 2]
old IN_VNAME'(' 	OS=[y(, l=, z(, p*]	PF=[a(, n, a), sqrt(, 2]
old IN_START'n' 	OS=[y(, l=, z(, p*, z(]	PF=[a(, n, a), sqrt(, 2, a(]
old IN_VNAME'-' 	OS=[y(, l=, z(, p*, z(]	PF=[a(, n, a), sqrt(, 2, a(]
old IN_START'-' 	OS=[y(, l=, z(, p*, z(]	PF=[a(, n, a), sqrt(, 2, a(, n]
old IN_START'1' 	OS=[y(, l=, z(, p*, z(, m-]	PF=[a(, n, a), sqrt(, 2, a(, n]
old IN_NUMBR')' 	OS=[y(, l=, z(, p*, z(, m-]	PF=[a(, n, a), sqrt(, 2, a(, n]
old IN_START')' 	OS=[y(, l=, z(, p*, z(, m-]	PF=[a(, n, a), sqrt(, 2, a(, n, 1]
old IN_CLOSE')' 	OS=[y(, l=, z(, p*]	PF=[a(, n, a), sqrt(, 2, a(, n, 1, -, a)]
old IN_START')' 	OS=[y(, l=, z(, p*]	PF=[a(, n, a), sqrt(, 2, a(, n, 1, -, a)]
old IN_CLOSE'+' 	OS=[y(, l=]	PF=[a(, n, a), sqrt(, 2, a(, n, 1, -, a), *, sqrt)]
old IN_START'+' 	OS=[y(, l=]	PF=[a(, n, a), sqrt(, 2, a(, n, 1, -, a), *, sqrt)]
old IN_START'A' 	OS=[y(, l=, m+]	PF=[a(, n, a), sqrt(, 2, a(, n, 1, -, a), *, sqrt)]
old IN_VNAME'1' 	OS=[y(, l=, m+]	PF=[a(, n, a), sqrt(, 2, a(, n, 1, -, a), *, sqrt)]
old IN_VNAME'2' 	OS=[y(, l=, m+]	PF=[a(, n, a), sqrt(, 2, a(, n, 1, -, a), *, sqrt)]
old IN_VNAME'3' 	OS=[y(, l=, m+]	PF=[a(, n, a), sqrt(, 2, a(, n, 1, -, a), *, sqrt)]
old IN_VNAME'4' 	OS=[y(, l=, m+]	PF=[a(, n, a), sqrt(, 2, a(, n, 1, -, a), *, sqrt)]
old IN_VNAME'5' 	OS=[y(, l=, m+]	PF=[a(, n, a), sqrt(, 2, a(, n, 1, -, a), *, sqrt)]
old IN_VNAME'6' 	OS=[y(, l=, m+]	PF=[a(, n, a), sqrt(, 2, a(, n, 1, -, a), *, sqrt)]
old IN_VNAME'(' 	OS=[y(, l=, m+]	PF=[a(, n, a), sqrt(, 2, a(, n, 1, -, a), *, sqrt)]
old IN_START'n' 	OS=[y(, l=, m+, z(]	PF=[a(, n, a), sqrt(, 2, a(, n, 1, -, a), *, sqrt), A123456(]
old IN_VNAME'*' 	OS=[y(, l=, m+, z(]	PF=[a(, n, a), sqrt(, 2, a(, n, 1, -, a), *, sqrt), A123456(]
old IN_START'*' 	OS=[y(, l=, m+, z(]	PF=[a(, n, a), sqrt(, 2, a(, n, 1, -, a), *, sqrt), A123456(, n]
old IN_OPTOR'2' 	OS=[y(, l=, m+, z(]	PF=[a(, n, a), sqrt(, 2, a(, n, 1, -, a), *, sqrt), A123456(, n]
old IN_START'2' 	OS=[y(, l=, m+, z(, p*]	PF=[a(, n, a), sqrt(, 2, a(, n, 1, -, a), *, sqrt), A123456(, n]
old IN_NUMBR')' 	OS=[y(, l=, m+, z(, p*]	PF=[a(, n, a), sqrt(, 2, a(, n, 1, -, a), *, sqrt), A123456(, n]
old IN_START')' 	OS=[y(, l=, m+, z(, p*]	PF=[a(, n, a), sqrt(, 2, a(, n, 1, -, a), *, sqrt), A123456(, n, 2]
old IN_CLOSE')' 	OS=[y(, l=, m+]	PF=[a(, n, a), sqrt(, 2, a(, n, 1, -, a), *, sqrt), A123456(, n, 2, *, A123456)]
old IN_START')' 	OS=[y(, l=, m+]	PF=[a(, n, a), sqrt(, 2, a(, n, 1, -, a), *, sqrt), A123456(, n, 2, *, A123456)]
result postfix=[a(, n, a), sqrt(, 2, a(, n, 1, -, a), *, sqrt), A123456(, n, 2, *, A123456), +, =]
;a(;n;a);sqrt(;2;a(;n;1;-;a);*;sqrt);A123456(;n;2;*;A123456);+;=
