IN_NAME,a, 	operStack=[], 	postfix=[]
IN_START,(, 	operStack=[], 	postfix=[a()]
IN_START,(, 	operStack=[y(], 	postfix=[a()]
IN_NAME,n, 	operStack=[y(], 	postfix=[a()]
IN_START,), 	operStack=[y(], 	postfix=[a(), n]
IN_CLOSE,), 	operStack=[], 	postfix=[a(), n]
IN_CLOSE, , 	operStack=[], 	postfix=[a(), n]
IN_START,=, 	operStack=[], 	postfix=[a(), n]
IN_OPERATOR,=, 	operStack=[], 	postfix=[a(), n]
IN_OPERATOR, , 	operStack=[], 	postfix=[a(), n]
IN_START,s, 	operStack=[l=], 	postfix=[a(), n]
IN_NAME,s, 	operStack=[l=], 	postfix=[a(), n]
IN_NAME,q, 	operStack=[l=], 	postfix=[a(), n]
IN_NAME,r, 	operStack=[l=], 	postfix=[a(), n]
IN_NAME,t, 	operStack=[l=], 	postfix=[a(), n]
IN_START,(, 	operStack=[l=], 	postfix=[a(), n, sqrt()]
IN_START,(, 	operStack=[l=, y(], 	postfix=[a(), n, sqrt()]
IN_NUMBER,2, 	operStack=[l=, y(], 	postfix=[a(), n, sqrt()]
IN_START,*, 	operStack=[l=, y(], 	postfix=[a(), n, sqrt(), 2]
IN_OPERATOR,*, 	operStack=[l=, y(], 	postfix=[a(), n, sqrt(), 2]
IN_START,a, 	operStack=[l=, y(, p*], 	postfix=[a(), n, sqrt(), 2]
IN_NAME,a, 	operStack=[l=, y(, p*], 	postfix=[a(), n, sqrt(), 2]
IN_START,(, 	operStack=[l=, y(, p*], 	postfix=[a(), n, sqrt(), 2, a()]
IN_START,(, 	operStack=[l=, y(, p*, y(], 	postfix=[a(), n, sqrt(), 2, a()]
IN_NAME,n, 	operStack=[l=, y(, p*, y(], 	postfix=[a(), n, sqrt(), 2, a()]
IN_START,-, 	operStack=[l=, y(, p*, y(], 	postfix=[a(), n, sqrt(), 2, a(), n]
IN_START,-, 	operStack=[l=, y(, p*, y(, m-], 	postfix=[a(), n, sqrt(), 2, a(), n]
IN_NUMBER,1, 	operStack=[l=, y(, p*, y(, m-], 	postfix=[a(), n, sqrt(), 2, a(), n]
IN_START,), 	operStack=[l=, y(, p*, y(, m-], 	postfix=[a(), n, sqrt(), 2, a(), n, 1]
IN_CLOSE,), 	operStack=[l=, y(, p*], 	postfix=[a(), n, sqrt(), 2, a(), n, 1, -]
IN_START,), 	operStack=[l=, y(, p*], 	postfix=[a(), n, sqrt(), 2, a(), n, 1, -]
IN_CLOSE,), 	operStack=[l=], 	postfix=[a(), n, sqrt(), 2, a(), n, 1, -, *]
IN_CLOSE, , 	operStack=[l=], 	postfix=[a(), n, sqrt(), 2, a(), n, 1, -, *]
IN_START,+, 	operStack=[l=], 	postfix=[a(), n, sqrt(), 2, a(), n, 1, -, *]
IN_START,+, 	operStack=[l=, m+], 	postfix=[a(), n, sqrt(), 2, a(), n, 1, -, *]
IN_START, , 	operStack=[l=, m+], 	postfix=[a(), n, sqrt(), 2, a(), n, 1, -, *]
IN_NAME,A, 	operStack=[l=, m+], 	postfix=[a(), n, sqrt(), 2, a(), n, 1, -, *]
IN_NAME,1, 	operStack=[l=, m+], 	postfix=[a(), n, sqrt(), 2, a(), n, 1, -, *]
IN_NAME,2, 	operStack=[l=, m+], 	postfix=[a(), n, sqrt(), 2, a(), n, 1, -, *]
IN_NAME,3, 	operStack=[l=, m+], 	postfix=[a(), n, sqrt(), 2, a(), n, 1, -, *]
IN_NAME,4, 	operStack=[l=, m+], 	postfix=[a(), n, sqrt(), 2, a(), n, 1, -, *]
IN_NAME,5, 	operStack=[l=, m+], 	postfix=[a(), n, sqrt(), 2, a(), n, 1, -, *]
IN_NAME,6, 	operStack=[l=, m+], 	postfix=[a(), n, sqrt(), 2, a(), n, 1, -, *]
IN_START,(, 	operStack=[l=, m+], 	postfix=[a(), n, sqrt(), 2, a(), n, 1, -, *, A123456()]
IN_START,(, 	operStack=[l=, m+, y(], 	postfix=[a(), n, sqrt(), 2, a(), n, 1, -, *, A123456()]
IN_NAME,n, 	operStack=[l=, m+, y(], 	postfix=[a(), n, sqrt(), 2, a(), n, 1, -, *, A123456()]
IN_START,*, 	operStack=[l=, m+, y(], 	postfix=[a(), n, sqrt(), 2, a(), n, 1, -, *, A123456(), n]
IN_OPERATOR,*, 	operStack=[l=, m+, y(], 	postfix=[a(), n, sqrt(), 2, a(), n, 1, -, *, A123456(), n]
IN_START,2, 	operStack=[l=, m+, y(, p*], 	postfix=[a(), n, sqrt(), 2, a(), n, 1, -, *, A123456(), n]
IN_NUMBER,2, 	operStack=[l=, m+, y(, p*], 	postfix=[a(), n, sqrt(), 2, a(), n, 1, -, *, A123456(), n]
IN_START,), 	operStack=[l=, m+, y(, p*], 	postfix=[a(), n, sqrt(), 2, a(), n, 1, -, *, A123456(), n, 2]
IN_CLOSE,), 	operStack=[l=, m+], 	postfix=[a(), n, sqrt(), 2, a(), n, 1, -, *, A123456(), n, 2, *]
result postfix=[a(), n, sqrt(), 2, a(), n, 1, -, *, A123456(), n, 2, *, +, =]
[a(), n, sqrt(), 2, a(), n, 1, -, *, A123456(), n, 2, *, +, =]
