old IN_START'(' 	OS=[]	PF=[]
old IN_START'1' 	OS=[y(]	PF=[]
old IN_NUMBER'-' 	OS=[y(]	PF=[]
old IN_START'-' 	OS=[y(]	PF=[1]
old IN_START'4' 	OS=[y(, m-]	PF=[1]
old IN_NUMBER'x' 	OS=[y(, m-]	PF=[1]
old IN_START'x' 	OS=[y(, m-, p*]	PF=[1, 4]
old IN_VNAME'(' 	OS=[y(, m-, p*]	PF=[1, 4]
old IN_START'(' 	OS=[y(, m-, p*]	PF=[1, 4, x, *]
old IN_START'1' 	OS=[y(, m-, p*, y(]	PF=[1, 4, x, *]
old IN_NUMBER'+' 	OS=[y(, m-, p*, y(]	PF=[1, 4, x, *]
old IN_START'+' 	OS=[y(, m-, p*, y(]	PF=[1, 4, x, *, 1]
old IN_START'x' 	OS=[y(, m-, p*, y(, m+]	PF=[1, 4, x, *, 1]
old IN_VNAME')' 	OS=[y(, m-, p*, y(, m+]	PF=[1, 4, x, *, 1]
old IN_START')' 	OS=[y(, m-, p*, y(, m+]	PF=[1, 4, x, *, 1, x]
old IN_CLOSE'^' 	OS=[y(, m-, p*]	PF=[1, 4, x, *, 1, x, +]
old IN_START'^' 	OS=[y(, m-, p*]	PF=[1, 4, x, *, 1, x, +]
old IN_START'2' 	OS=[y(, m-, p*, q^]	PF=[1, 4, x, *, 1, x, +]
old IN_NUMBER')' 	OS=[y(, m-, p*, q^]	PF=[1, 4, x, *, 1, x, +]
old IN_START')' 	OS=[y(, m-, p*, q^]	PF=[1, 4, x, *, 1, x, +, 2]
result postfix=[1, 4, x, *, 1, x, +, 2, ^, *, -]
[1, 4, x, *, 1, x, +, 2, ^, *, -]
