IN_START,(, 	operStack=[y(], 	postfix=[]
IN_NUMBER,1, 	operStack=[y(], 	postfix=[]
IN_START,-, 	operStack=[y(], 	postfix=[1]
IN_START,-, 	operStack=[y(, m-], 	postfix=[1]
IN_NUMBER,4, 	operStack=[y(, m-], 	postfix=[1]
IN_START,x, 	operStack=[y(, m-, p*], 	postfix=[1, 4]
IN_NAME,x, 	operStack=[y(, m-, p*], 	postfix=[1, 4]
IN_START,(, 	operStack=[y(, m-, p*], 	postfix=[1, 4, x, *]
IN_START,(, 	operStack=[y(, m-, p*, y(], 	postfix=[1, 4, x, *]
IN_NUMBER,1, 	operStack=[y(, m-, p*, y(], 	postfix=[1, 4, x, *]
IN_START,+, 	operStack=[y(, m-, p*, y(], 	postfix=[1, 4, x, *, 1]
IN_START,+, 	operStack=[y(, m-, p*, y(, m+], 	postfix=[1, 4, x, *, 1]
IN_NAME,x, 	operStack=[y(, m-, p*, y(, m+], 	postfix=[1, 4, x, *, 1]
IN_START,), 	operStack=[y(, m-, p*, y(, m+], 	postfix=[1, 4, x, *, 1, x]
IN_CLOSE,), 	operStack=[y(, m-, p*], 	postfix=[1, 4, x, *, 1, x, +]
IN_START,^, 	operStack=[y(, m-, p*], 	postfix=[1, 4, x, *, 1, x, +]
IN_START,^, 	operStack=[y(, m-, p*, q^], 	postfix=[1, 4, x, *, 1, x, +]
IN_NUMBER,2, 	operStack=[y(, m-, p*, q^], 	postfix=[1, 4, x, *, 1, x, +]
IN_START,), 	operStack=[y(, m-, p*, q^], 	postfix=[1, 4, x, *, 1, x, +, 2]
IN_CLOSE,), 	operStack=[], 	postfix=[1, 4, x, *, 1, x, +, 2, ^, *, -]
result postfix=[1, 4, x, *, 1, x, +, 2, ^, *, -]
[1, 4, x, *, 1, x, +, 2, ^, *, -]
