old IN_START'(' 	OS=[]	PF=[]
old IN_START'2' 	OS=[y(]	PF=[]
old IN_NUMBR'*' 	OS=[y(]	PF=[]
old IN_START'*' 	OS=[y(]	PF=[2]
old IN_OPTOR'n' 	OS=[y(]	PF=[2]
old IN_START'n' 	OS=[y(, p*]	PF=[2]
old IN_VNAME'*' 	OS=[y(, p*]	PF=[2]
old IN_START'*' 	OS=[y(, p*]	PF=[2, n]
old IN_OPTOR'a' 	OS=[y(, p*]	PF=[2, n]
old IN_START'a' 	OS=[y(, p*]	PF=[2, n, *]
old IN_VNAME'(' 	OS=[y(, p*]	PF=[2, n, *]
old IN_START'n' 	OS=[y(, p*, z(]	PF=[2, n, *, a(]
old IN_VNAME')' 	OS=[y(, p*, z(]	PF=[2, n, *, a(]
old IN_START')' 	OS=[y(, p*, z(]	PF=[2, n, *, a(, n]
old IN_CLOSE'+' 	OS=[y(, p*]	PF=[2, n, *, a(, n, a)]
old IN_START'+' 	OS=[y(, p*]	PF=[2, n, *, a(, n, a)]
old IN_START'(' 	OS=[y(, m+]	PF=[2, n, *, a(, n, a), *]
old IN_START'-' 	OS=[y(, m+, y(]	PF=[2, n, *, a(, n, a), *]
old IN_START'2' 	OS=[y(, m+, y(, m-]	PF=[2, n, *, a(, n, a), *, 0]
old IN_NUMBR'3' 	OS=[y(, m+, y(, m-]	PF=[2, n, *, a(, n, a), *, 0]
old IN_NUMBR'*' 	OS=[y(, m+, y(, m-]	PF=[2, n, *, a(, n, a), *, 0]
old IN_START'*' 	OS=[y(, m+, y(, m-]	PF=[2, n, *, a(, n, a), *, 0, 23]
old IN_OPTOR'n' 	OS=[y(, m+, y(, m-]	PF=[2, n, *, a(, n, a), *, 0, 23]
old IN_START'n' 	OS=[y(, m+, y(, m-, p*]	PF=[2, n, *, a(, n, a), *, 0, 23]
old IN_VNAME'+' 	OS=[y(, m+, y(, m-, p*]	PF=[2, n, *, a(, n, a), *, 0, 23]
old IN_START'+' 	OS=[y(, m+, y(, m-, p*]	PF=[2, n, *, a(, n, a), *, 0, 23, n]
old IN_START'3' 	OS=[y(, m+, y(, m+]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -]
old IN_NUMBR'6' 	OS=[y(, m+, y(, m+]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -]
old IN_NUMBR')' 	OS=[y(, m+, y(, m+]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -]
old IN_START')' 	OS=[y(, m+, y(, m+]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36]
old IN_CLOSE'*' 	OS=[y(, m+]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +]
old IN_START'*' 	OS=[y(, m+]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +]
old IN_OPTOR'a' 	OS=[y(, m+]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +]
old IN_START'a' 	OS=[y(, m+, p*]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +]
old IN_VNAME'(' 	OS=[y(, m+, p*]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +]
old IN_START'n' 	OS=[y(, m+, p*, z(]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(]
old IN_VNAME'-' 	OS=[y(, m+, p*, z(]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(]
old IN_START'-' 	OS=[y(, m+, p*, z(]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n]
old IN_START'1' 	OS=[y(, m+, p*, z(, m-]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n]
old IN_NUMBR')' 	OS=[y(, m+, p*, z(, m-]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n]
old IN_START')' 	OS=[y(, m+, p*, z(, m-]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1]
old IN_CLOSE'+' 	OS=[y(, m+, p*]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a)]
old IN_START'+' 	OS=[y(, m+, p*]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a)]
old IN_START'6' 	OS=[y(, m+]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a), *, +]
old IN_NUMBR'*' 	OS=[y(, m+]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a), *, +]
old IN_START'*' 	OS=[y(, m+]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a), *, +, 6]
old IN_OPTOR'(' 	OS=[y(, m+]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a), *, +, 6]
old IN_START'(' 	OS=[y(, m+, p*]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a), *, +, 6]
old IN_START'-' 	OS=[y(, m+, p*, y(]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a), *, +, 6]
old IN_START'2' 	OS=[y(, m+, p*, y(, m-]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a), *, +, 6, 0]
old IN_NUMBR'*' 	OS=[y(, m+, p*, y(, m-]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a), *, +, 6, 0]
old IN_START'*' 	OS=[y(, m+, p*, y(, m-]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a), *, +, 6, 0, 2]
old IN_OPTOR'n' 	OS=[y(, m+, p*, y(, m-]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a), *, +, 6, 0, 2]
old IN_START'n' 	OS=[y(, m+, p*, y(, m-, p*]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a), *, +, 6, 0, 2]
old IN_VNAME'+' 	OS=[y(, m+, p*, y(, m-, p*]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a), *, +, 6, 0, 2]
old IN_START'+' 	OS=[y(, m+, p*, y(, m-, p*]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a), *, +, 6, 0, 2, n]
old IN_START'3' 	OS=[y(, m+, p*, y(, m+]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a), *, +, 6, 0, 2, n, *, -]
old IN_NUMBR')' 	OS=[y(, m+, p*, y(, m+]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a), *, +, 6, 0, 2, n, *, -]
old IN_START')' 	OS=[y(, m+, p*, y(, m+]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a), *, +, 6, 0, 2, n, *, -, 3]
old IN_CLOSE'*' 	OS=[y(, m+, p*]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a), *, +, 6, 0, 2, n, *, -, 3, +]
old IN_START'*' 	OS=[y(, m+, p*]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a), *, +, 6, 0, 2, n, *, -, 3, +]
old IN_OPTOR'a' 	OS=[y(, m+, p*]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a), *, +, 6, 0, 2, n, *, -, 3, +]
old IN_START'a' 	OS=[y(, m+, p*]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a), *, +, 6, 0, 2, n, *, -, 3, +, *]
old IN_VNAME'(' 	OS=[y(, m+, p*]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a), *, +, 6, 0, 2, n, *, -, 3, +, *]
old IN_START'n' 	OS=[y(, m+, p*, z(]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a), *, +, 6, 0, 2, n, *, -, 3, +, *, a(]
old IN_VNAME'-' 	OS=[y(, m+, p*, z(]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a), *, +, 6, 0, 2, n, *, -, 3, +, *, a(]
old IN_START'-' 	OS=[y(, m+, p*, z(]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a), *, +, 6, 0, 2, n, *, -, 3, +, *, a(, n]
old IN_START'2' 	OS=[y(, m+, p*, z(, m-]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a), *, +, 6, 0, 2, n, *, -, 3, +, *, a(, n]
old IN_NUMBR')' 	OS=[y(, m+, p*, z(, m-]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a), *, +, 6, 0, 2, n, *, -, 3, +, *, a(, n]
old IN_START')' 	OS=[y(, m+, p*, z(, m-]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a), *, +, 6, 0, 2, n, *, -, 3, +, *, a(, n, 2]
old IN_CLOSE'=' 	OS=[y(, m+, p*]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a), *, +, 6, 0, 2, n, *, -, 3, +, *, a(, n, 2, -, a)]
old IN_START'=' 	OS=[y(, m+, p*]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a), *, +, 6, 0, 2, n, *, -, 3, +, *, a(, n, 2, -, a)]
old IN_OPTOR'0' 	OS=[y(, m+, p*]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a), *, +, 6, 0, 2, n, *, -, 3, +, *, a(, n, 2, -, a)]
old IN_START'0' 	OS=[y(, l=]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a), *, +, 6, 0, 2, n, *, -, 3, +, *, a(, n, 2, -, a), *, +]
old IN_NUMBR')' 	OS=[y(, l=]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a), *, +, 6, 0, 2, n, *, -, 3, +, *, a(, n, 2, -, a), *, +]
old IN_START')' 	OS=[y(, l=]	PF=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a), *, +, 6, 0, 2, n, *, -, 3, +, *, a(, n, 2, -, a), *, +, 0]
result postfix=[2, n, *, a(, n, a), *, 0, 23, n, *, -, 36, +, a(, n, 1, -, a), *, +, 6, 0, 2, n, *, -, 3, +, *, a(, n, 2, -, a), *, +, 0, =]
;2;n;*;a(;n;a);*;0;23;n;*;-;36;+;a(;n;1;-;a);*;+;6;0;2;n;*;-;3;+;*;a(;n;2;-;a);*;+;0;=
