old IN_START'(' 	OS=[]	PF=[]
old IN_START'm' 	OS=[y(]	PF=[]
old IN_VNAME'o' 	OS=[y(]	PF=[]
old IN_VNAME'd' 	OS=[y(]	PF=[]
old IN_VNAME'(' 	OS=[y(]	PF=[]
old IN_START'1' 	OS=[y(, z(]	PF=[]
old IN_NUMBR'7' 	OS=[y(, z(]	PF=[]
old IN_NUMBR',' 	OS=[y(, z(]	PF=[]
old IN_START',' 	OS=[y(, z(]	PF=[17]
old IN_START'5' 	OS=[y(, z(, i,]	PF=[17]
old IN_NUMBR')' 	OS=[y(, z(, i,]	PF=[17]
old IN_START')' 	OS=[y(, z(, i,]	PF=[17, 5]
old IN_CLOSE'+' 	OS=[y(]	PF=[17, 5, ,, mod()]
old IN_START'+' 	OS=[y(]	PF=[17, 5, ,, mod()]
old IN_START'2' 	OS=[y(, m+]	PF=[17, 5, ,, mod()]
old IN_NUMBR'm' 	OS=[y(, m+]	PF=[17, 5, ,, mod()]
old IN_START'm' 	OS=[y(, m+, p*]	PF=[17, 5, ,, mod(), 2]
old IN_VNAME'o' 	OS=[y(, m+, p*]	PF=[17, 5, ,, mod(), 2]
old IN_VNAME'd' 	OS=[y(, m+, p*]	PF=[17, 5, ,, mod(), 2]
old IN_VNAME'(' 	OS=[y(, m+, p*]	PF=[17, 5, ,, mod(), 2]
old IN_START'1' 	OS=[y(, m+, p*, z(]	PF=[17, 5, ,, mod(), 2]
old IN_NUMBR'8' 	OS=[y(, m+, p*, z(]	PF=[17, 5, ,, mod(), 2]
old IN_NUMBR',' 	OS=[y(, m+, p*, z(]	PF=[17, 5, ,, mod(), 2]
old IN_START',' 	OS=[y(, m+, p*, z(]	PF=[17, 5, ,, mod(), 2, 18]
old IN_START'1' 	OS=[y(, m+, p*, z(, i,]	PF=[17, 5, ,, mod(), 2, 18]
old IN_NUMBR'0' 	OS=[y(, m+, p*, z(, i,]	PF=[17, 5, ,, mod(), 2, 18]
old IN_NUMBR')' 	OS=[y(, m+, p*, z(, i,]	PF=[17, 5, ,, mod(), 2, 18]
old IN_START')' 	OS=[y(, m+, p*, z(, i,]	PF=[17, 5, ,, mod(), 2, 18, 10]
old IN_CLOSE')' 	OS=[y(, m+, p*]	PF=[17, 5, ,, mod(), 2, 18, 10, ,, mod()]
old IN_START')' 	OS=[y(, m+, p*]	PF=[17, 5, ,, mod(), 2, 18, 10, ,, mod()]
result postfix=[17, 5, ,, mod(), 2, 18, 10, ,, mod(), *, +]
;17;5;,;mod();2;18;10;,;mod();*;+
