java.util.EmptyStackException
	at java.util.Stack.peek(Unknown Source)
	at java.util.Stack.pop(Unknown Source)
	at org.teherba.ramath.symbolic.PolynomialParser.parseFrom(PolynomialParser.java:557)
	at org.teherba.ramath.symbolic.Polynomial.<init>(Polynomial.java:147)
	at org.teherba.ramath.symbolic.RelationSet.<init>(RelationSet.java:111)
	at org.teherba.ramath.symbolic.RelationSet.<init>(RelationSet.java:137)
	at org.teherba.ramath.symbolic.RelationSet.parse(RelationSet.java:581)
	at org.teherba.ramath.symbolic.solver.TreeSolver.main(TreeSolver.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.teherba.common.RegressionTester.runTests(RegressionTester.java:495)
	at org.teherba.common.RegressionTester.main(RegressionTester.java:586)
